name: functional-networking
on:
  pull_request:
    paths:
      - '**networking**'
  schedule:
    - cron: '0 0 * * *'
jobs:
  functional-networking:
    strategy:
      fail-fast: false
      matrix:
        name: ["master"]
        openstack_version: ["master"]
        ubuntu_version: ["20.04"]
        devstack_conf_overrides: [""]
        include:
          - name: "yoga"
            openstack_version: "stable/yoga"
            ubuntu_version: "20.04"
            devstack_conf_overrides: ""
          - name: "xena"
            openstack_version: "stable/xena"
            ubuntu_version: "20.04"
            devstack_conf_overrides: ""
          - name: "wallaby"
            openstack_version: "stable/wallaby"
            ubuntu_version: "20.04"
            devstack_conf_overrides: ""
          - name: "victoria"
            openstack_version: "stable/victoria"
            ubuntu_version: "20.04"
            devstack_conf_overrides: ""
          - name: "ussuri"
            openstack_version: "stable/ussuri"
            ubuntu_version: "18.04"
            devstack_conf_overrides: |
              enable_plugin neutron-fwaas https://git.openstack.org/openstack/neutron-fwaas stable/ussuri
          - name: "train"
            openstack_version: "stable/train"
            ubuntu_version: "18.04"
            devstack_conf_overrides: |
              enable_plugin neutron-fwaas https://git.openstack.org/openstack/neutron-fwaas stable/train
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Deploy OpenStack ${{ matrix.name }} with Neutron and run networking acceptance tests
    steps:
      - name: Checkout Gophercloud
        uses: actions/checkout@v3
      - name: Deploy devstack
        uses: EmilienM/devstack-action@v0.7
        with:
          branch: ${{ matrix.openstack_version }}
          conf_overrides: |
            Q_ML2_PLUGIN_EXT_DRIVERS=qos,port_security,dns_domain_keywords
            enable_plugin neutron-vpnaas https://opendev.org/openstack/neutron-vpnaas ${{ matrix.openstack_version }}
            enable_plugin neutron-dynamic-routing https://opendev.org/openstack/neutron-dynamic-routing  ${{ matrix.openstack_version }}
            ${{ matrix.devstack_conf_overrides }}
          enabled_services: 'neutron-dns,neutron-qos,neutron-segments,neutron-trunk,neutron-uplink-status-propagation,neutron-network-segment-range,neutron-port-forwarding'
      - name: Checkout go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.15'
      - name: Run Gophercloud acceptance tests
        run: ./script/acceptancetest
        env:
          DEVSTACK_PATH: ${{ github.workspace }}/devstack
          ACCEPTANCE_TESTS_FILTER: "^.*networking.*$"
          OS_BRANCH: ${{ matrix.openstack_version }}
      - name: Generate logs on failure
        run: ./script/collectlogs
        if: failure()
      - name: Upload logs artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: functional-networking-${{ matrix.name }}
          path: /tmp/devstack-logs/*
