name: Verify PR Labels
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 1
          labels: "semver:patch, semver:minor, semver:major"
